spring:
  datasource:
    username: ""
    password: ""
    url: "jdbc:h2:./voting"

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  h2:
    console:
      enabled: true
      path: /h2console/
      settings:
        web-allow-others: true

logging:
  level:
    root: INFO
    web: DEBUG