spring:
  datasource:
    username: ""
    password: ""
    url: "jdbc:h2:./voting"

  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.H2Dialect

  h2:
    console:
      enabled: true
      path: /h2console/
      settings:
        web-allow-others: true

logging:
  level:
    root: INFO
    web: DEBUG